# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 22:03
from __future__ import unicode_literals
from django.db import migrations, models
import pandas as pd


def initialize_rater_data(apps, schema_editor):
    Rater = apps.get_model('ratingbase', 'Rater')

    raters = pd.read_csv(
        '/Users/Oakes/Desktop/data/users.dat',
        sep='::', names=['rater_id', 'gender', 'age', 'occ', 'zip_code'],
        header=None)

    for row in raters.iterrows():
        row = row[1].to_dict()
        new = Rater(rater_id=int(row['rater_id']), gender=row['gender'],
                    age=int(row['age']), occupation=int(row['occ']),
                    zip_code=row['zip_code'])
        new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0003_auto_20160504_2202'),
    ]

    operations = [
        migrations.RunPython(initialize_rater_data),
    ]
