# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 22:10
from __future__ import unicode_literals
from django.db import migrations, models
import pandas as pd


def initialize_movie_data(apps, schema_editor):
    Movie = apps.get_model('ratingbase', 'Movie')

    movies = pd.read_csv(
        '/Users/Oakes/Desktop/data/movies.dat',
        sep='::', names=['movie_id', 'title', 'genre'],
        header=None)

    for row in movies.iterrows():
        row = row[1].to_dict()
        new = Movie(movie_id=int(row['movie_id']), title=row['movie_id'],
                    genre=row['genre'])
        new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0005_auto_20160504_2210'),
    ]

    operations = [
        migrations.RunPython(initialize_movie_data),
    ]
