# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0007_auto_20160504_2216'),
    ]

    operations = [
    ]
