# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0008_auto_20160504_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
