# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0012_movie_avg_rating'),
    ]

    operations = [
    ]
