# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:27
from __future__ import unicode_literals

from django.db.models import Avg
from django.db import models, migrations


def calculate_avg(apps, schema_editor):
    Movie = apps.get_model('ratingbase', 'Movie')
    Rater = apps.get_model('ratingbase', 'Rater')
    Rating = apps.get_model('ratingbase', 'Rating')

    for movie in Movie.objects.all():
        ratings = Rating.objects.filter(movie=movie)
        avg = ratings.aggregate(Avg('rating'))
        movie.avg_rating = avg['rating__avg']
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0012_movie_avg_rating'),
    ]

    operations = [
        migrations.RunPython(calculate_avg),

    ]
