# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0013_auto_20160505_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings_count',
            field=models.IntegerField(null=True),
        ),
    ]
