# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:34
from __future__ import unicode_literals

from django.db import models, migrations


def get_ratings_count(apps, schema_editor):
    Movie = apps.get_model('ratingbase', 'Movie')
    Rating = apps.get_model('ratingbase', 'Rating')

    for movie in Movie.objects.all():
        ratings = Rating.objects.filter(movie=movie)
        movie.ratings_count = ratings.count()
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0014_movie_ratings_count'),
    ]

    operations = [
        migrations.RunPython(get_ratings_count),
    ]
