# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingbase', '0018_auto_20160509_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('rater', 'movie')]),
        ),
    ]
